package pack.admin.model;

import pack.controller.*;
import pack.model.*;

import java.util.List;

public interface AdminInter {

	AdminDto getAdminLoginInfo(String adminid);
	boolean insertBookData(NewBookBean bean);
	List<NewBookDto> getNewBook();
	List<UserDto> getUser();
	List<OldBookDto> getSellOb();
	List<OldBookDto> getStandby();
	List<OldBookDto> getReuse();
	boolean updateState(OldBookBean bean);
	List<OldBookDto> getRBook();
	List<OrderInfoDto> getnbOrderData();
	List<OrderInfoDto> getobOrderData();
	List<RentInfoDto> getRentList();
	List<UserDto> getUserPoint();
	List<OrderInfoDto> getNobank();
	boolean updateOrderState(OrderInfoBean bean);
	List<OrderInfoDto> getOrderData();
	boolean updateThrow(int ob_no);
	List<RentInfoDto> getDelayData();
	boolean updateUser(UserBean bean);
	boolean removeOb(int ob_no);
	List<String> getDelayId();
	boolean updateDcount(String user_id);
	List<UserDto> getDelay();
	boolean updatePenalty(UserBean bean);
	List<UserDto> getRefuse();
	List<UserDto> getUserdel();
	List<UserDto> getUsercheck();
	boolean updateDelUser(String user_id);
	List<OrderInfoDto> getDelayDeposit();
	boolean delOrder(String orderlist_no);
	boolean insertFaqData(FaqBoardBean bean);
	List<FaqBoardDto> getFaqlist();
	List<InqueryDto> getinqlist();
	List<ReviewDto> getreviewAll();
	List<OrderInfoDto> getProfit();
	List<OrderInfoDto> getObProfit();
	List<OrderInfoDto> getNbProfit();
	OrderInfoDto getObProfitmonth();
	OrderInfoDto getNbProfitmonth();
	OrderInfoDto getProfitmonth();
	List<AdminDto> getAdminyet();
	boolean delAdmin(String admin_id);
	boolean upAdmin(AdminBean bean);
	List<AdminDto> getAdminInfo();
	boolean upAdminJik(AdminBean bean);
	List<ReviewDto> getBestReview();
	List<ReviewDto> getBestReviewmonth(String sql);
	List<ReviewDto> getRmonth();
	boolean upUserPoint(UserBean bean);
	List<NewBookDto> getOmonth();
	List<NewBookDto> getOcmonth();
	List<NewBookDto> getBestSellermonth(String sql);
	boolean upNbStock(NewBookBean bean);
	List<RentInfoDto> getRentmonth();
	List<RentInfoDto> getRentcmonth();
	List<RentInfoDto> getBestRentmonth(String sql);
	String getMonth();
	List<RentInfoDto> getRentKing();
	List<OrderInfoDto> getBuyKing();
	InqueryDto getInqData(int inq_no);
	InqueryDto getMaxNum();
	boolean upOnum(InqueryBean bean);
	boolean insInqReply(InqueryBean bean);
	boolean RollbackStock(NewBookBean bean);
	List<NewBookDto> theMostSellBook();
	List<OldBookDto> theMostRentBook();
	String IdCheck(String admin_id);
	boolean insertAdmin(AdminBean bean);
	boolean insChartData(ChartPrintBean bean);
	String getChartmonth(String cmonth);
	boolean upChartData(ChartPrintBean bean);
	boolean updateAdmin(AdminBean bean);
}
