server:
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/static/**
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true